"""add passports visa_policies history news_triggers

Revision ID: c3c18482598f
Revises: f02359424756
Create Date: 2026-03-16 14:48:57.546473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3c18482598f'
down_revision: Union[str, None] = 'f02359424756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affected_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_triggers_status'), 'news_triggers', ['status'], unique=False)
    op.create_table('passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passports_country_id'), 'passports', ['country_id'], unique=False)
    op.create_table('visa_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passport_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('visa_category', sa.String(length=20), nullable=False),
    sa.Column('max_stay_days', sa.Integer(), nullable=True),
    sa.Column('visa_validity_days', sa.Integer(), nullable=True),
    sa.Column('processing_days', sa.Integer(), nullable=True),
    sa.Column('fee_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_policies_destination_id'), 'visa_policies', ['destination_id'], unique=False)
    op.create_index(op.f('ix_visa_policies_passport_id'), 'visa_policies', ['passport_id'], unique=False)
    op.create_index(op.f('ix_visa_policies_visa_category'), 'visa_policies', ['visa_category'], unique=False)
    op.create_table('visa_policy_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('visa_category', sa.String(length=20), nullable=False),
    sa.Column('max_stay_days', sa.Integer(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['visa_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_policy_history_policy_id'), 'visa_policy_history', ['policy_id'], unique=False)
    op.drop_constraint('countries_iso2_key', 'countries', type_='unique')
    op.drop_index('ix_countries_iso2', table_name='countries')
    op.create_index(op.f('ix_countries_iso2'), 'countries', ['iso2'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_iso2'), table_name='countries')
    op.create_index('ix_countries_iso2', 'countries', ['iso2'], unique=False)
    op.create_unique_constraint('countries_iso2_key', 'countries', ['iso2'])
    op.drop_index(op.f('ix_visa_policy_history_policy_id'), table_name='visa_policy_history')
    op.drop_table('visa_policy_history')
    op.drop_index(op.f('ix_visa_policies_visa_category'), table_name='visa_policies')
    op.drop_index(op.f('ix_visa_policies_passport_id'), table_name='visa_policies')
    op.drop_index(op.f('ix_visa_policies_destination_id'), table_name='visa_policies')
    op.drop_table('visa_policies')
    op.drop_index(op.f('ix_passports_country_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_news_triggers_status'), table_name='news_triggers')
    op.drop_table('news_triggers')
    # ### end Alembic commands ###
